### ISSUE TITLE
Frends.Oracle.ExecuteQuery

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.Oracle#1]
Make sure to look at current community task and to also make this like the current MSSQL official task, so that they look alike.

NB! Oracle already exists really and we should create a branch with current state of things, e.g. "Archive" or something. Then redo the whole repo to new way of doing things.

**Comment by RikuVirtanen** [comment]
Created initial implementation of Frends.Oracle.ExecuteQuery Task that targets .net6.0 and follows the newest guidelines of Frends Tasks implementation. #3
