### ISSUE TITLE
ExecuteQuery - make query properties first tab and connection properties second

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.Oracle#7]
1. Make query properties first tab and connection properties second.
2. Make sure that query field is preselected to be SQL type field.
3. Make sure that connection string is preselected to be of Text type field.

**Comment by RikuVirtanen** [comment]
I have merged the query and connection properties tabs like in other database related tasks. I have fixed those other issues also in PR #8

**Comment by RikuVirtanen** [comment]
Fixed in PR #8
